name = "spotify-worker"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"

[build]
command = "node build.js"

# The necessary secrets are:
# - SPOTIFY_CLIENT_ID
# - SPOTIFY_CLIENT_SECRET
# - SPOTIFY_REFRESH_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
